# Shell variables
# Generated by 'wal'
wallpaper='/home/rmoses/dotfiles/.config/hypr/themes/cosmic_watcher/watcher_of_the_cosmic_gate.jpg'

# Special
background='#0c090a'
foreground='#cac1ca'
cursor='#cac1ca'

# Colors
color0='#0c090a'
color1='#614D65'
color2='#6B536E'
color3='#85647A'
color4='#775187'
color5='#8D6F92'
color6='#A252B0'
color7='#cac1ca'
color8='#8d878d'
color9='#614D65'
color10='#6B536E'
color11='#85647A'
color12='#775187'
color13='#8D6F92'
color14='#A252B0'
color15='#cac1ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
