theme:
  lightTheme: false 
  activeBorderColor:
    - "#8bd5ca" # Green
    - bold
  inactiveBorderColor:
    - "#cad3f5" # Text
  optionsTextColor:
    - "#8aadf4" # Blue
  selectedLineBgColor:
    - "#8bd5ca" # Surface0
  selectedRangeBgColor:
    - "#8bd5ca" # Surface0
  cherryPickedCommitBgColor:
    - "#8bd5ca" # Teal
  cherryPickedCommitFgColor:
    - "#8aadf4" # Blue
  unstagedChangesColor:
    - red       # Red
