# Suppress the newline between modules
add_newline = false

# Format the prompt with custom layout
format = """
$git_branch$git_status
$directory$fill$time
"""

# Git Branch: show only in Git repos
[git_branch]
format = "[$branch]($style) "
style = "bold purple"
only_in_repo = true

# Git Status: show only in Git repos
[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "red"
only_in_repo = true

# Directory config
[directory]
truncation_length = 1
truncate_to_repo = false
style = "cyan"
format = "[\\[$path\\]]($style) "
# Custom logic to display ../<folder> style after 40 chars
read_only = " 🔒"
home_symbol = "~"
truncation_symbol = "../"

# Use the fill module to right-align time
[fill]
symbol = " "

# Time module on the right
[time]
disabled = false
format = "[$time]($style)"
style = "bold yellow"
time_format = "%H:%M"  # Or use "%T" for full time

